### PR TITLE
Add two new tags

### PR DESCRIPTION
**Pull request by SableWalnut**
This PR adds two of the tags mentioned in #32! :)

### CODE REVIEW

**Comment by timheap** [comment]
Nice! Can you add some tests to check that the tags appear if the setting exists?

**Comment by SableWalnut** [comment]
@timheap Added tests! :)

**Comment by timheap** [comment]
You didn't activate a virtualenv with this package installed before editing, so your editors automatic isort has shuffled some imports. Check the diff, specifically in the tests file.

**Comment by SableWalnut** [comment]
@timheap fixed up! :)

**Comment by SalahAdDin** [comment]
@SableWalnut Hey, thanks!

**Comment by SalahAdDin** [comment]
Guys! what's about this?

**Comment by SalahAdDin** [comment]
@timheap What's about it? Long time ago.

**Pull request merged**
