### PR TITLE
No global defaults for description and image

### PR DESCRIPTION
**Pull request by timheap**
As discussed in #23, global defaults do more harm than good. The defaults have been removed. This left `SiteMetadataPreferences` being kinda pointless, so it was also removed, along with the admin views and URLs.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
But, doesn't it delete all features? This doesn't use wagtail hooks for register menú in admin, and others...

**Comment by timheap** [comment]
You can still use the MetadataPageMixin, which is the most useful part of this plugin. The defaults in SiteMetadataPreferences were not useful, so were removed.

**Comment by SalahAdDin** [comment]
Does leave it with same functionality?

**Comment by timheap** [comment]
Rebased to resolve merge conflicts, updated the README to remove SiteMetadataPreferences references

**Comment by SalahAdDin** [comment]
But, how can we change metadata options?

**Comment by timheap** [comment]
Each page should inherit from `MetadataPageMixin`. For each page, you can set the description using `search_description`, and the image using `search_image`.

**Comment by SalahAdDin** [comment]
Please update the documentation, so, no more global metadata, now each page have own metadata, and when we declare this page in code we put metadata, right?

**Pull request merged**
